apiVersion: v2
name: monitoring-stack
description: My local monitoring stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "66.3.1"  # Check artifacthub.io for the latest
    repository: "https://prometheus-community.github.io/helm-charts"
